#fs      = require 'fs'
#{exec}  = require 'child_process'

require 'icing'

pub = 'public'

coffees = [
  'script/*.coffee'
]

jades = [
  'index.jade',
  #'projects/*.jade'
]

lesses = [
  'style/style.less'
]

assets = [
  'img/*.jpg'
  'img/*.png'
  'script/libs/'
  'style/bootstrap/'
  'style/fonts/'
  'style/style.less'
]

logTask = (ctx, name) ->
  mods = ctx.modifiedPrereqs.length
  tot = ctx.filePrereqs.length
  console.log "Building #{name} files (#{mods} mod / #{tot} total)"

task 'build:coffee', 'Build all coffee into js', coffees,
  outputs: ->
    for file in this.filePrereqs
      file.replace /\.coffee/, '.js'
      "pub/#{file}"
  recipe: ->
    logTask this, "coffee"
    this.exec "coffee --compile -o #{pub}/script #{this.modifiedPrereqs.join(' ')}"

task 'build:jade', 'Build all jade into html', jades,
  outputs: ->
    #if (/^projects\//.test file)
    for file in this.filePrereqs
      file.replace /\.jade/, '.html'
      "pub/#{file}"
  recipe: ->
    logTask this, "jade"
    for file in this.modifiedPrereqs
      # TODO
      #this.exec "jade < #{file} --path #{file} > #{pub}/#{file}"
      this.exec "jade #{file} --out #{pub}"

task 'build', 'Build all coffee, jade, and less',
  ['task(build:coffee)', 'task(build:jade)'],
  -> this.finished()

task 'export', 'Move all assets', [assets, 'task(build)'], ->
  for file in this.modifiedPrereqs
    this.exec "cp -r #{file} #{pub}/#{file}"

#task 'build:less', 'Build all jade into html', ->
#  console.log "Building less files"
#  for file in styles
#    exec "lessc #{file} > #{file}.css", (err, stdout, stderr) ->
#      throw err if err
